web:
#  upload-path: /usr/fileTest/
  upload-path: D://file/


server:
  port: 8011
  servlet:
    session:
      timeout: 10m


spring:
  datasource:
    username: wtdbuser
    password: wtdbuser
    url: jdbc:mysql://bj-cdb-hgkqwllz.sql.tencentcdb.com:63308/test_tb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: file:${web.upload-path}
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxhy.saas.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
#  path: /usr/testLog
  path: D://file/log

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true



